services:
  server:
    image: ghcr.io/kevinlhuillier/node-test:latest
    ports:
      - 8080:80
    pull_policy: always
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure