name: CI/CD

#env:
  #SERVER_USER: "root"
  #SERVER_STAGING: "78.138.45.88"
  #SERVER_PRODUCTION: "54.37.11.162"
env:
  #OWNER_LC: 'kevinlhuillier'
  SERVER_PRODUCTION_IP: "57.129.42.227"
  SERVER_PRODUCTION_USER: "root"

#concurrency: 
  #group: ${{ github.workflow }}-${{ github.ref }}
  #cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      #- name: set lower case owner name
      #  run: |
      #    echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mise en place de Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login sur GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Récupération des métadonnées
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/kevinlhuillier/node-test

      - name: Build et push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/kevinlhuillier/node-test:latest
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: http://$SERVER_PRODUCTION_IP
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Déployer sur le serveur de production
        run : |
              eval $(ssh-agent -s)
              ssh-add - <<< "${{ secrets.VPS_KEY}}"
              mkdir -p ~/.ssh
              ssh-keyscan -H ${{ env.SERVER_PRODUCTION_IP}} >> ~/.ssh/known_hosts
              scp docker-compose.production.yml ${{ env.SERVER_PRODUCTION_USER }}@${{ env.SERVER_PRODUCTION_IP}}:/root/docker-compose.production.yml
              ssh ${{ env.SERVER_PRODUCTION_USER }}@${{ env.SERVER_PRODUCTION_IP}} "docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}"
              ssh ${{ env.SERVER_PRODUCTION_USER }}@${{ env.SERVER_PRODUCTION_IP}} "docker compose -f /root/docker-compose.production.yml up -d --force-recreate"
